# Generated by Django 3.0.5 on 2020-04-14 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('contacted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Recieved Messages',
            },
        ),
    ]
