# Generated by Django 3.0.5 on 2020-04-12 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('item_photo', models.ImageField(upload_to='')),
                ('author', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
